version: '3.4'

services:
  nodedockerapi:
    image: nodedockerapi
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 9229:9229
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: